version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    volumes:
      - uploads:/usr/src/app/uploads
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGHOST : "${PGHOST}"
      PGPASSWORD: "${PGPASSWORD}"
      PGPORT: "${PGPORT}"
      PGDATABASE: "${PGDATABASE}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      PORT: 80
      SESSION_SECRET: secret
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    ports:
      - "80:80"
    networks:
      - default
    links:
      - database
      - redis

  database:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGHOST : "${PGHOST}"
      PGPASSWORD: "${PGPASSWORD}"
      PGPORT: "${PGPORT}"
      PGDATABASE: "${PGDATABASE}"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fonebahia8@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'

volumes:
  postgres:
  uploads:
